version: "3.1"
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - backend
    links:
      - rabbitmq
      - courier_location
  courier_location:
    build: ./courier-location
    restart: always
    hostname: courier_location
    env_file:
      - .env
    networks:
      - backend
    links:
      - db
      - redis
  courier_location_event:
    build: ./courier-location-event
    restart: always
    hostname: courier_location_event
    env_file:
      - .env
    networks:
      - backend
    links:
      - rabbitmq
      - courier_location
  db:
    image: "mongo"
    command: [mongod]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - "./db/data/db-files:/data/db"
      - "./db/init/:/docker-entrypoint-initdb.d/"
    ports:
      - 27017:27017
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend
networks:
  backend:
    driver: bridge
